name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Create deployment package
        run: tar -czf norris.kg.tar.gz .next public messages

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: norris.kg
          path: norris.kg.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: norris.kg

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 77.235.20.172 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp -P 2609 norris.kg.tar.gz daniGitAction@77.235.20.172:/var/www/html/norris/
          ssh -p 2609 daniGitAction@77.235.20.172 << 'EOF'
            cd /var/www/html/norris
            tar -xzf norris.kg.tar.gz
            rm norris.kg.tar.gz
            yarn install --production
            pm2 restart your-app-name || pm2 start npm --name "your-app-name" -- start
          EOF
